export const CUSTOMER_DETAILS = "CUSTOMER_DETAILS";
export const ADD_TO_CART = "ADD_TO_CART";
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY";
export const DECREMENT_QUANITY = "DECREMENT_QUANITY";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
